[client]
toolbarMode = "minimal"
showErrorDetails = false

[logger]
level = "error"

[server]
maxUploadSize = 200

[theme]
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
